version: "3"
services:

  statsd:
    build: .
    ports:
    - 8125:8125/udp
    - 8126:8126
    depends_on:
    - graphite

  graphite:
    image: graphiteapp/graphite-statsd:1.1.7-11
    container_name: graphite
    restart: always
    ports:
    - 8000:80
    - 2003-2004:2003-2004
    - 2023-2024:2023-2024
    - 8125:8125/udp
    - 8126:8126
